### PR TITLE
remove sudo calls as script must be run as root

### PR DESCRIPTION
**Pull request by tmornini**
This patch eliminates:

    sudo: sorry, you must have a tty to run sudo

exceptions when configuring Loggly via an AWS EC2 user data script.

Since ```checkIfUserHasRootPrivileges()``` on https://github.com/loggly/install-script/blob/master/Linux%20Script/configure-linux.sh#L190 requires script to be run as root the use of sudo is entirely superfluous. :-)

Until this patch is accepted, we're correcting in the user data script via:

    sed -i.original 's/sudo //' configure-linux.sh

### CODE REVIEW

**Comment by tmornini** [comment]
Ping

**Comment by mostlyjason** [comment]
@psquickitjayant can you review this one? Probably good for you to watch this repo too. I noticed some formatting changes.

**Comment by tmornini** [comment]
@mostlyjason Hurray! Thanks for paying attention. :-)

**Comment by tmornini** [comment]
Ping

**Comment by psquickitjayant** [comment]
sorry I missed it. I will check it now :)

**Comment by tmornini** [comment]
@psquickitjayant Ping

**Comment by psquickitjayant** [comment]
@tmornini  I have added this in my backlog. I am doing changes in the script. Once done, then will merge you changes.

**Comment by tmornini** [comment]
@psquickitjayant Are you joking? This has been outstanding since September!

Why don't you merge the patch and rebase your changes atop master?

**Comment by mostlyjason** [comment]
How does this work for users who are not on EC2, for example if they are running as a non-root user on their own linux installation? It seems we need something that works for them too. If there is a way, we'd have to test it on other distributions too.

**Comment by tmornini** [comment]
@mostlyjason Please read PR description again.

This script REQUIRES that it be run as root. As such, there's zero need to use sudo. :-(

**Comment by mostlyjason** [comment]
@psquickitjayant is this deployed now? if so, we can close

**Comment by psquickitjayant** [comment]
yes @mostlyjason

**Comment by jmckee46** [comment]
@mostlyjason @psquickitjayant This repository is out-of-date, i.e. the Linux configure script () does not match what's here.

```
[ec2-user@ip-10-0-2-107 test]$ curl https://www.loggly.com/install/configure-linux.sh | sha256sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25960  100 25960    0     0  48265      0 --:--:-- --:--:-- --:--:-- 48342
9ff4c007070199f6da53077c889ea4ba8f48557a2cab9fba197f2be63ee1127d  -
[ec2-user@ip-10-0-2-107 test]$ curl https://raw.githubusercontent.com/loggly/install-script/master/Linux%20Script/configure-linux.sh | sha256sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25620  100 25620    0     0  79333      0 --:--:-- --:--:-- --:--:-- 79318
0bbce5ad2dbdd2a62785d789f790163f2e17b26310710e1fa4dcd70c1e01fd99  -
```

**Comment by jmckee46** [comment]
Wow, the script at https://www.loggly.com/install/configure-linux.sh not only differs with respect to sudo handling, but it entirely changes the semantics of the script in at least two ways:

1) It no longer runs verification as it used to.

2) APP_TAG is now destroyed on line 21, making it impossible(?) to set APP_TAG.
```
APP_TAG=
```

**Comment by mostlyjason** [comment]
@psquickitjayant can you test and confirm what @jmckee46 says? We want verification and the tags to work.

**Comment by psquickitjayant** [comment]
@mostlyjason  @jmckee46  APP_TAG is a property which is used by the other scripts like apache, tomcat, etc. 

It does not go for the verification steps if there are not any changes in the 22-loggly.conf file and it already exists. 

If you do a fresh install, or if there are any changes in 22-loggly.conf then verification steps run.

**Comment by mchaudhary** [comment]
We have already made the changes to remove the sudo from the script and make sure the script is run as root.

**Comment by tmornini** [comment]
Wow, fantastic, only took 1 month for first response and 7 months to close.

And no merge, giving no credit or thanks for my pull request.

You folks are truly living the open source dream! :-(

**Comment by mostlyjason** [comment]
@tmornini sorry about that! Thanks for your contribution! I think our forks are out of sync so we merged it in https://github.com/psquickitjayant/install-script. I'm not sure which commit it was in though. Hopefully we'll get this one synced up soon.

**Pull request closed without merging**
