### PR TITLE
use "curl -L" to follow redirects during subdomain check

### PR DESCRIPTION
**Pull request by jmpesp**
also write out http_code to avoid using grep to check for 200

### CODE REVIEW

**Comment by OndrejCholeva** [comment]
sorry to say, but unfortunately this is not correct solution:
```
curl -L -s --head  --request GET invalid23424.loggly.com/login -w '%{http_code}' -o /dev/null
```

still outputs 200. This is due to invalid subdomain follows redirect to an error page, which surprisingly returns 200 and html code....

**Comment by jmpesp** [comment]
@OndrejCholeva @nguyenfilip I originally made this PR because our scripts were failing at this subdomain check step - a 302 is seen because loggly now redirects to another page for auth.

I had no idea that an invalid subdomain redirects to a valid error page! We can use curl's -w again here though, to check that the redirect isn't invalid:
```
$ curl -Ls -o /dev/null -w %{url_effective} invalid45862456294756239846984918345074562975.loggly.com
https://invalid45862456294756239846984918345074562975.loggly.com/accounts/invalid
$ curl -Ls -o /dev/null -w %{url_effective} testpost.loggly.com
https://my.solarwinds.cloud/login?nonce=S3DECsSQ8rbykxpC&state=eyJvcmlnaW5hdGluZ19vcmdfaWQiOiBudWxsLCAicmZwIjogIjVXY2lxeDAxYWZTaDBrWk4iLCAic3ViZG9tYWluIjogInRlc3Rwb3N0IiwgInJldHVybl9wYXRoIjogIi8ifQ%3D%3D&redirect_uri=https%3A%2F%2Fapp.loggly.com%2Fsso%2Foidc%2Fdo_sign_on&response_type=code&client_id=loggly&scope=openid+swicus
```
I'll make another PR with this check.

**Comment by OndrejCholeva** [comment]
@jmpesp https://github.com/loggly/install-script/pull/122 covers that already ;-) cheers.

**Comment by jmpesp** [comment]
Nevermind, https://github.com/loggly/install-script/pull/122 handles it :)

ninja edit: @OndrejCholeva is quicker on the draw :)

**Pull request merged**
